trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
- group: Release Management Resources
- group: RELEASE das-apim-developer-web
- name: SolutionBaseName
  value: SFA.DAS.Apim.Developer.Web
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.22
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.5.6
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-apim-developer-web
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM
      SolutionBaseName: $(SolutionBaseName)

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-apim-developer-web
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST
      ServiceConnection: SFA-DAS-DevTest-ARM
      SolutionBaseName: $(SolutionBaseName)

- stage: Deploy_TEST2
  dependsOn: Build
  displayName: Deploy to TEST2
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  - group: TEST2 das-apim-developer-web
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST2
      ServiceConnection: SFA-DAS-DevTest-ARM
      SolutionBaseName: $(SolutionBaseName)

##TO DO: link PROD das-apim-developer-web variable group to Deploy_PROD stage
## test
